language: python

env: 
  global: 
    - SWMM_HOME=`pwd`
    - BUILD_HOME=build
    - TEST_HOME=nrtestsuite

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libboost-test-dev
  - sudo apt-get install -y swig 

#install:

before_script:
  - mkdir -p $BUILD_HOME
  - cd $BUILD_HOME
  - cmake ..

script:
  - cmake --build .
  # run unit tests
  - cd tests
  - ctest
  - cd $SWMM_HOME
  # install dependencies for nrtest
  - pip install --src build/packages -r tools/requirements.txt
  # run regression tests
  - tools/before-test.sh $TEST_HOME $SWMM_HOME/$BUILD_HOME/bin $TRAVIS_COMMIT
  - tools/run-nrtest.sh $TEST_HOME $TRAVIS_COMMIT
