#ifndef VERSION_H
#define VERSION_H

#define PROJECT_NAME "epaswmm"
#define PROJECT_VERSION_MAJOR 5
#define PROJECT_VERSION_MINOR 3
#define PROJECT_VERSION_PATCH 0
#define PROJECT_VERSION "5.3.0"
#define PROJECT_VERSION_SWMM_FORMAT (PROJECT_VERSION_MAJOR * 10000 + PROJECT_VERSION_MINOR * 1000 + PROJECT_VERSION_PATCH)
#define BUILD_ID ""
#define BUILD_COMMIT ""
#define BUILD_BRANCH ""
#define BUILD_DATE ""

#endif // VERSION_H
